### ISSUE TITLE
How should I prepare the `coords_3D.npy` file?

### ISSUE THREAD

**Issue by LZUzgw** [Aurora132/VolumeNeRF#1]
Thank you for your outstanding work. I carefully ran `simulate_DRR.py` following your instructions. However, when running `train.py`, I encountered an error: `No such file or directory: './DRR_Parameters/coords_3D.npy'`. I went back to check `simulate_DRR.py` but found no code to save this file. Could you please let me know how I should prepare the `coords_3D.npy` file?

**Comment by LZUzgw** [comment]
In the renderers.py file, I commented out `self.coor3d = np.load(coor_path).astype(np.float32)` and `self.coor3d = nn.Parameter(data=torch.from_numpy(self.coor3d).to(device), requires_grad=False)`, and the problem was solved.

**Comment by WorldWide2001** [comment]
Hello, may I ask if this project can be reproduced?
